const URLS = {
  userToken: '',
  HOST_URL: 'https://superadmin.mandreducation.in',
  SUFFIX_URL: '/api/v1',
  DASHBOARD: () => `/super-admins/dashboard`,
  GET_PLAN: (searchInput, pageSize) =>
    `/plans?search=${searchInput}&page_size=${pageSize}`,
  GET_ADMINS: () => `/superadmin/admins`,
  ADD_PLAN: () => `/plans`,
  EDIT_PLAN: id => `/plans/${id}`,
  EDIT_ADMIN: id => `/superadmin/admins/${id}`,
  UPDATE_PLAN: id => `/plans/${id}`,
  DELETE_PLAN: id => `/plans/${id}`,
  UPDATE_USERNAME: () => `/change-username`,
  UPDATE_PHONE: () => `/change-phone`,
  UPDATE_EMAIL: () => `/change-email`,
  UPDATE_PASSWORD: () => `/change-password`,
  LOGIN: `/login`,
  LOG_OUT: `/logout`,
  GET_PROFILE: '/profile',
  UPDATE_PROFILE: () => '/profile/update',
  CHANGE_PASSWORD: '/change-password',
  FORGOT_PASSWORD: '/password/email',
  RESET_PASSWORD: token => `/password/reset?token=${token}`,
  ADD_ADMIN: () => `/superadmin/admins`,
  UPDATE_ADMIN: id => `/admins/${id}`,
  UPDATE_STUDENT_COUNT: id => `/superadmin/admins/student-count/${id}`,
  ADD_ADMIN_PLAN: id => `/superadmin/admins/add-plan/${id}`,
  ADD_ADMIN_FEATURES: id => `/superadmin/admins/add-features/${id}`,
  DELETE_ADMIN: id => `/superadmin/admins/destroy/${id}`,
  GET_STATES: '/states',
  GET_CITIES: '/cities',
  MAKE_PAYMENT: () => '/make-payment',
  ADD_FEATURE: () => `/features`,
  GET_FEATURES: (searchInput, pageSize) =>
    `/features?search=${searchInput}&page_size=${pageSize}`,
  GET_FEATURES_LIST: '/features',
  FEATURE_BY_ID: id => `/features/${id}`,
  UPDATE_FEATURE: id => `/features/${id}`,
  DELETE_FEATURE: id => `/features/${id}`,
  ADD_QUESTION_BANK: () => `/addQuestions`,
  GET_QUESTION_BANK: () => `/questionbanks`,
  GET_ALL_COURSESDATA: () => `/getallcoursedata`,
  EDIT_QUESTION_BANK: id => `/questionbanks/edit/${id}`,
  UPDATE_QUESTION_BANK: id => `/questionbanks/${id}`,
  DELETE_QUESTION_BANK: id => `/questionbanks/${id}`,
  ADD_COURSE: () => `/courses`,
  GET_COURSE: (searchInput, pageSize) =>
    `/courses?search=${searchInput}&page_size=${pageSize}`,
  GET_COURSE_LIST: '/courses',
  EDIT_COURSE: id => `/courses/${id}`,
  DELETE_COURSE: id => `/courses/${id}`,
  ADD_SUBJECT: () => `/subjects`,
  GET_SUBJECT: (searchInput, pageSize, courseId) =>
    `/subjects?search=${searchInput}&page_size=${pageSize}&course_id=${courseId}`,
  GET_SUBJECT_LIST: '/subjects',
  SUBJECT_BY_ID: id => `/subjects/${id}`,
  UPDATE_SUBJECT: id => `/subjects/${id}`,
  DELETE_SUBJECT: id => `/subjects/${id}`,
  ADD_CHAPTER: () => `/chapters`,
  GET_CHAPTER: (searchInput, pageSize, courseId, subjectId) =>
    `/chapters?search=${searchInput}&page_size=${pageSize}&course_id=${courseId}&subject_id=${subjectId}`,
  GET_CHAPTER_LIST: '/chapters',
  CHAPTER_BY_ID: id => `/chapters/${id}`,
  UPDATE_CHAPTER: id => `/chapters/${id}`,
  DELETE_CHAPTER: id => `/chapters/${id}`,
  GET_CONTENT: (searchInput, pageSize) =>
    `/materials?search=${searchInput}&page=${pageSize}`,
  ADD_CONTENT: () => `/materials`,
  CONTENT_BY_ID: id => `/materials/${id}`,
  CONTENT_LOCKED: id => `/materials/islocked/${id}`,
  ADD_LANGUAGES: () => `/languages`,
  GET_LANGUAGES: () => `/languages`,
  EDIT_LANGUAGES: id => `/languages/${id}`,
  UPDATE_LANGUAGES: id => `/languages/${id}`,
  DELETE_LANGUAGES: id => `/languages/${id}`,
  ADD_ACADEMIC_YEAR: () => `/academic-years`,
  GET_ACADEMIC_YEAR: () => `/academic-years`,
  EDIT_ACADEMIC_YEAR: id => `/academic-years/${id}`,
  UPDATE_ACADEMIC_YEAR: id => `/academic-years/${id}`,
  DELETE_ACADEMIC_YEAR: id => `/academic-years/${id}`,
  GET_NOTIFICATIION: (searchInput, pageSize) =>
    `/notifications?search=${searchInput}&page_size=${pageSize}`,
  ADD_NOTIFICATION: () => `/notifications`,
  EDIT_NOTIFICATION: id => `/notifications/${id}`,
  DELETE_NOTIFICATION: id => `/notifications/${id}`,
  GET_PAYMENT_HISTORY: (searchInput, pageSize) =>
    `/get-payment-history?search=${searchInput}&page_size=${pageSize}`,
};
export default URLS;
